mp:                                                         # Multiprocessing configuration
    processes:                  4                           # Number of parallel processes to use (should be equal to number of cores)
    report:                     1                           # Report progress every N seconds

meteors:
    count:                      1

    shape:
        dragCoefficient:        0.6                         # 0.6 for a spherical body
        shapeFactor:            1.21                        # 1.21 for a spherical body

    material:
        density:
            distribution:       'constant'
            parameters:
                value:          3000 
        heatTransfer:           0.5                         # Heat transfer coefficient, default 0.5
        ablationHeat:           6000000                     # Specific enthalpy of vaporization, in J/kg

    mass:
        distribution:           constant                    # Particle mass distribution. Possible values 'pareto', 'exponential' or a number
        parameters:
            value:              0.0001
#            minimum:            0.000001                    # Minimum particle mass, in kg
#            shape:              1.80                        # Shape of the distribution, corresponds to s-index (N(m) \propto m^-s)

    position:
        distribution:           'rectangle'                 # Name of the distribution, currently only 'rectangle'
        parameters:
            south:              49                          # Southern bound, degrees of latitude
            north:              49                          # Northern bound, degrees of latitude
            west:               20                          # Western bound, degrees of longitude
            east:               20                          # Eastern bound, degrees of longitude
            elevation:          150000                      # Initial elevation of meteors, in m

    velocity:
        distribution:           'shower'                    # Currently only 'shower'
        parameters:
            ra:                 43                          # Right ascension in degrees
            dec:                56                          # Declination in degrees
            speed:              59000                       # Entry speed in m/s

    time:
        distribution:           'uniform'
        parameters:
            begin:              2016-08-11T20:00:00         # Beginning of the interval, ISO8601
            end:                2016-08-11T20:00:00         # End of the interval, ISO8601

    integrator:                                             
        name:                   'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
        fps:                    20                          # Frames per second
        spf:                    1                           # Steps per frame. Higher values result in more precise trajectories but increase computation time
