campaign:
    observers:
        ago:
            latitude:           48.3729
            longitude:          17.2738
            altitude:           531
            horizon:            0
            name:               'AGO'
